BUFFER_SIZE = 2048
INVALID_REQUEST_CODE = "0"
INVALID_REQUEST_ERROR = "Invalid req_code"
KEYBOARD_MESSAGE_EXIT = "\nPress any key to exit."
GET_MESSAGE = "GET"

MAX_QUEUED_CONNECTIONS = 10
SERVER_DONE_MESSAGES = "NO MSG."
SERVER_END_MESSAGE = "TERMINATE"
SERVER_LOOP_TIMEOUT = 1