from enum import Enum


FOREVER=True
TRACKER_PORT_CONNECT_ATTEMPTS=12
MIN_PORT_NUMBER=20000
MAX_PORT_NUMBER=60000
MESSAGE_SEPARATOR = " "

class MessageCode(Enum):
    PEER_DISCONNECT = 1
    PEER_ACQUIRED_FILE = 2
    NEW_CHUNK_IN_SYSTEM = 3
    FILE_CHUNK = 4
